config/routes.rb
Rails.application.routes.draw do
  # Static Pages
  root 'pages#home'
  get '/about', to: 'pages#about', as: :about_page
  get '/home', to: 'pages#home', as: :home_page

  resources :users
  resources :conversations, shallow: true, except: %i(create) do
    resources :messages
  end

  post 'conversations/:user_id', to: 'conversations#find_or_create'

  resource :session, only: %i{new create destroy}

  mount ActionCable.server => '/cable'
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :conversation_users, dependent: :destroy
  has_many :users, through: :conversation_users

  has_many :messages, through: :conversation_users, dependent: :destroy

  validates :conversation_users, presence: true, length: { is: 2, message: 'should be exactly 2' }
  validate :not_a_duplicate?

  def self.exactly_between(*users)
    ids = users.pluck(:id).map(&:to_i)
    Conversation.
      joins(:users).
      group('id').
      where(users: { id: ids }).
      having('count(*) = ?', users.length)
  end

  def title
    Conversation.includes(:users).find(id).users.map(&:full_name).join(' - ')
  end

  private

  def not_a_duplicate?
    if Conversation.exactly_between(*users).any?
      errors.add(:base, 'A conversation already exists between these users')
      false
    else
      true
    end
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :require_login
  before_action :set_conversation, only: [:show, :edit, :update]

  # GET /conversations
  # GET /conversations.json
  def index
    @conversations = current_user.conversations
  end

  # GET /conversations/1
  # GET /conversations/1.json
  def show
  end

  # GET /conversations/1/edit
  def edit
  end

  # POST /conversations/1
  # POST /conversations/1.json
  def find_or_create
    other_user = User.find(params[:user_id])
    @conversation = Conversation.exactly_between( current_user, other_user ).first || Conversation.create( users: [ current_user, other_user ] )

    respond_to do |format|
      if @conversation
        format.json { redirect_to conversation_messages_url(@conversation) }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_conversation
    @conversation = Conversation.find(params[:id])
  end
end

app/views/conversations/_form.html.slim
= form_for @conversation do |f|
  - if @conversation.errors.any?
    #error_explanation
      h2 = "#{pluralize(@conversation.errors.count, "error")} prohibited this conversation from being saved:"
      ul
        - @conversation.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :sender_id
    = f.text_field :sender_id
  .field
    = f.label :recipient_id
    = f.text_field :recipient_id
  .actions = f.submit

app/views/conversations/edit.html.slim
h1 Editing conversation

= form_for @conversation do |f|
  .actions = f.submit

= link_to 'Show', @conversation
'  |
= link_to 'Back', conversations_path(current_user)

app/views/conversations/index.html.slim
h1 Listing conversations

table
  thead
    tr
      th Title
      th
      th

  tbody
    - @conversations.each do |conversation|
      tr
        td = link_to conversation.title, conversation_messages_path(conversation)
        td = link_to 'Show', conversation
        td = link_to 'Edit', edit_conversation_path(conversation)

app/views/conversations/show.html.slim
p#notice = notice

p
  strong= @conversation.title

= link_to 'Edit', edit_conversation_path(@conversation)
'  |
= link_to 'Back', conversations_path