config/routes.rb
Rails.application.routes.draw do
  # Static Pages
  root 'pages#home'
  get '/about', to: 'pages#about', as: :about_page
  get '/home', to: 'pages#home', as: :home_page

  resources :users
  resources :conversations, shallow: true, except: %i(create) do
    resources :messages
  end

  post 'conversations/:user_id', to: 'conversations#find_or_create'

  resource :session, only: %i{new create destroy}

  mount ActionCable.server => '/cable'
end

app/views/layouts/_navbar.slim
nav.navbar.container
  h1 Puerco
  ul
    - if logged_in?
      li
        = link_to current_user.email, user_path(current_user)
      li
        = link_to 'Log Out', session_path, method: :delete, class: 'bx_link'
      li
        = link_to 'Conversations', conversations_path, class: 'bk_link'
    - else
      li
        = link_to "Log In", new_session_path, class: 'bx_link'
      li
        = link_to "Sign Up", new_user_path, class: 'bx_link'

app/views/layouts/_notices.slim
- if flash[:error]
  .ui.error.message
    i.close.icon
    .header Error:
    p= flash[:error]

- if flash[:info]
  .ui.info.message
    i.close.icon
    .header Info:
    p= flash[:info]

- if flash[:success]
  .ui.success.message
    i.close.icon
    .header Success:
    p= flash[:success]

- if flash[:warning]
  .ui.warning.message
    i.close.icon
    .header Warning:
    p= flash[:warning]

app/views/layouts/_sidebar_link.slim
li.left-nav-list__item data-interior-left-nav-item="" role="menuitem" tabindex="0"
  = link_to conversation_path(user.id), remote: true, method: :post, class: 'left-nav-list__item-link' do
    = user.full_name
    .bx--appearance-online-icon data-user-appearance="#{user.id}" style="#{ user.online? ? '' : 'display: none;' }"
    message-tag data-message-notification="#{user.id}"

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Link
    = csrf_meta_tags

    = javascript_include_tag 'application',
      'data-turbolinks-track': 'reload'

    = stylesheet_pack_tag 'application',
      media: 'all',
      'data-turbolinks-track': 'reload'

    = javascript_pack_tag 'application',
      'data-turbolinks-track': 'reload'

  body *punchbox_data
    == render 'layouts/navbar'
    == render 'layouts/notices'
    == yield(:sublayout)
    main
      == yield

app/views/layouts/conversations.html.slim
- content_for(:sublayout) do
  nav.bx--interior-left-nav.bx--interior-left-nav--collapseable aria-label=("Interior Left Navigation") data-interior-left-nav="" role="navigation" 
    ul.left-nav-list aria-hidden="false" data-interior-left-nav-list="" role="menubar"
      - current_user.conversations.each do |conversation|
        == render partial: 'layouts/sidebar_link', locals: { conversation: conversation }

== render template: 'layouts/application'

app/views/layouts/messages.html.slim
- content_for(:sublayout) do
  nav.bx--interior-left-nav.bx--interior-left-nav--collapseable aria-label=("Interior Left Navigation") data-interior-left-nav="" role="navigation" 
    ul.left-nav-list aria-hidden="false" data-interior-left-nav-list="" role="menubar"
      - User.all.each do |user|
        == render partial: 'layouts/sidebar_link', locals: { user: user }

== render template: 'layouts/application'